# Generated by Django 4.2 on 2023-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokemons', '0007_alter_pokemon_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pokemons',
            field=models.ManyToManyField(to='app_pokemons.pokemon'),
        ),
    ]
