# Generated by Django 4.2 on 2023-04-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokemons', '0002_stats_type_remove_pokemon_type_pokemon_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddField(
            model_name='stats',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pokemons.pokemon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pokemons.pokemon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stats',
            name='stat_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=32),
        ),
    ]
