# Generated by Django 4.2 on 2023-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokemons', '0004_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ('stat_name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('type_name',)},
        ),
    ]
