# Generated by Django 4.2 on 2023-04-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokemons', '0005_alter_pokemon_options_alter_stats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={},
        ),
    ]
