# Generated by Django 4.2 on 2023-04-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pokemons', '0006_alter_pokemon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('name',)},
        ),
    ]
